services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - .env

  frontend:
    build: 
      context: ./client
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    depends_on:
      - backend
